### PR TITLE
Nuclear, Worldgen and Security

### LINKED ISSUE #26: World gen sometimes doesnt work and override custom preset
This is not because of terrablender, tectonic and ecosphere

### LINKED ISSUE #28: Changing cog wood type doesnt do anything
when applying wood plank to cogwheel, it doesnt change its woodtype and the small and large cogwheel (the one create has in the base game) doesnt have the custom textures

### LINKED ISSUE #31: Steam engine from steampowered isnt working
The steam engine from steampowered doesnt accept steam fluid even it's own, so it cannot spin the flywheel (sad!)

### PR DESCRIPTION
**Pull request by Bt111488**

### CODE REVIEW

**Comment by SLimeyMC** [comment]
Would you please list some of the block that won't be added?

Other than that, Radium and Canary do the same thing, please delete Canary and proceed by adding patchouli

**Comment by SLimeyMC** [comment]
Let's reduce the tier into reinforced, and remove all the coolant added by the Extreme Reactor.
There's room for discussion regarding the other multiblock structures, whether they are useful to the mod pack and 'create friendly'.

**Comment by SLimeyMC** [comment]
Also please make new branch for big changes

**Comment by Bt111488** [comment]
Definite multiblock remove, replace recipes made in these with custom as necessary:
Fluidizer 
Reprossecer

Turbines may or may not be removed

**Comment by SLimeyMC** [comment]
I will close this PR for incompleteness, please make a new PR once you're done with adding custom recipes, blocking some recipes add conversion tag and change block's name to match that in real life (make a new resource pack I will help you on that).

Make sure to add all the progress on nuclear branch, I will be reverting the main branch before the extreme reactor added

**Pull request closed without merging**
